data:
  train: "data/conll2003/train.json"
  valid: "data/conll2003/valid.json"
  test: "data/conll2003/test.json"
  dataset: "conll2003"

tokenizer:
  max_length: 512
  padding: True
  return_tensors: "pt"

model:
  name: "t5-base"

training:
  batch_size: 16
  learning_rate: 5e-5
  n_epoch: 10
  do_save_best_checkpoint: true
  metric_name: "f1-score"
  metric_avg: "weighted_avg"

evaluation:
  batch_size: 16

generation:
  num_beams: 2
  max_length: 128

seed: 23
replace_labels_with_special_tokens: false
