data:
  train: "data/conll2003/train.json"
  valid: "data/conll2003/valid.json"
  test: "data/conll2003/test.json"
  dataset: "conll2003"

model:
  name: "t5-base"
  batch_size: 16
  learning_rate: 5e-5
  beam_size: 2
  n_epoch: 1

tokenizer:
  max_length: 512
  padding: True
  return_tensors: "pt"

do_log: true
seed: 23
replace_labels_with_special_tokens: false
